name: Docker build SQL Edge
on:
  push:
    paths:
    - 'SqlEdgeSolution/modules/AzureSqlEdge/**'
  workflow_dispatch:
    inputs:
      comment:
        description: "Run comments"
        required: false
env:
  FILE: Dockerfile.amd64
  CONTEXT: ./SqlEdgeSolution/modules/AzureSqlEdge
  IMAGE_NAME: "marvingarcia/azure-sql-edge-developer"
  IMAGE_TAG: "tbd"
jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set image tag
        run: |
          echo "IMAGE_TAG=$(date +%y%m%d%H%M)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.CONTEXT }}/${{ env.FILE }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.IMAGE_NAME }}:latest
          push: true